# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - default
  - override dataset: MINDlarge
  - override model: GLORY
  - _self_

optimizer:
#  lr: 0.0002
  lr: 0.00006

num_epochs: 5
batch_size: 32            # dataloaders'batch_size = batch_size / gpu_num
accumulation_steps: 1   # final acutal batch_size = batch_size * accumulation_steps
gpu_num: 4

# load or not
load_checkpoint: false
load_mark: base_large
train_mode: true
val_mode: true

model:
  use_entity: true
  entity_neighbors: 10
  head_num: 20
  head_dim: 20
  use_graph_type: 0
  directed: true
  num_neighbors: 8
  k_hops: 2
  use_abs_entity: true
  use_subcategory_graph: true
  subcategory_neighbors: 5
  use_event: true
  event_use_abs_extraction: false
  use_key_entity: true
  subcategory_size: 286
  event_dict_size: 52
  key_entity_size: 8
  gru_layer_num: 1

logger:
  exp_name: FullModelLarge
  run_name: ${model.model_name}_${dataset.dataset_name}_${model.k_hops}-${model.num_neighbors}-${model.entity_neighbors}

ml_label: default

num_workers: 4
early_stop_patience: 5
reprocess: false
reprocess_neighbors: false
warmup_ratio: 0.1

val_skip_epochs: 1
val_steps: 10000
