# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - default
  - override dataset: MINDsmall
  - override model: GLORY
  - _self_




optimizer:
#  lr: 0.0002
#  lr: 0.00002
#  lr: 0.00006
  lr: 0.00007





num_epochs: 5
batch_size: 32            # dataloaders'batch_size = batch_size / gpu_num
accumulation_steps: 1     # final acutal batch_size = batch_size * accumulation_steps
gpu_num: 1

# load or not
load_checkpoint: false
#load_checkpoint: true
#load_mark: base_small
#load_mark: default_auc0.679425835609436 # event + subcategory + abs_entity + entity, gru layer = 3
#load_mark: default_auc0.6735262274742126  # 上个模型二次训练
train_mode: true
#train_mode: true
val_mode: true

model:
  use_entity: true
  entity_neighbors: 10
  head_num: 20
  head_dim: 20
  use_graph_type: 0
  directed: true
  num_neighbors: 8
  k_hops: 2
  use_abs_entity: true
  use_subcategory_graph: true
  subcategory_neighbors: 5
  use_event: true
  event_use_abs_extraction: false
  use_key_entity: true
  subcategory_size: 272
  event_dict_size: 50
  key_entity_size: 8
  gru_layer_num: 3
  use_HieRec: true
  topic_per_user: 8
  news_per_topic: 5
  subtopic_per_user: 15
  news_per_subtopic: 5
  word_emb_dim: 300
  use_hetero_graph: true


logger:
  exp_name: FullModel
  run_name: ${model.model_name}_${dataset.dataset_name}_${model.k_hops}-${model.num_neighbors}-${model.entity_neighbors}

ml_label: default

num_workers: 4
early_stop_patience: 5
reprocess: false
reprocess_neighbors: false
warmup_ratio: 0.1
log_steps: 1000

#val_skip_epochs: 0
#val_steps: 10
val_skip_epochs: 2
val_steps: 1000
